### PR TITLE
Upgrade syn to v1.0.81

### LINKED ISSUE #38: automated feedback - rust analyzer failed to parse
The rust analyzer detects a syntax error in my solution, although there is none.
https://exercism.org/tracks/rust/exercises/roman-numerals/solutions/geri1701

### PR DESCRIPTION
**Pull request by mcastorina**
Possibly closes #38

I'm not entirely sure if it is functionally correct, but it compiles and the tests pass.

### CODE REVIEW

**Comment by ErikSchierboom** [comment]
@mcastorina Your PR was just slightly later than @petertseng's [PR](https://github.com/exercism/rust-analyzer/pull/39), which I've just merged, sorry. I think the main difference is that you have a specific "1.0.81" version as the dependency, whereas @petertseng used "1.0". Is it worth being specific here @petertseng? If so, we could consider rebasing this PR on the latest main and updating the version.

**Comment by petertseng** [comment]
I did learn something new from this PR, in that it's possible to use `box` patterns, which could have saved me a few lines! So rebasing that particular change upon `main` would have benefits in saving a few lines, and should remain functionally equivalent.

From https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html, note that specifying "1.0.81" (which is interpreted as `>= 1.0.81 && < 2.0.0`) and 1.0 (which is interpreted as `>= 1.0.0 && < 2.0.0`) are almost the same (see they only differ in the minimum version; the maximum version is the same), so I have no opinion on which to use until/unless I become educated otherwise (and I am always open to being educated).

**Comment by petertseng** [comment]
I do see that `box` patterns are an unstable feature, so that means the build would need to use the nightly version of rustc.

**Comment by mcastorina** [comment]
No worries! It was a good exercise in refactoring foreign code :)

**Pull request closed without merging**
